### PR TITLE
add getters to EventHubConsumerGroup

### PR DESCRIPTION
**Pull request by kostat**

### CODE REVIEW

**Comment by rtandonmsft** [comment]
@kostat Can you please remove custom and rather make it as 0.9.1. I also noticed you changed EventHubSender to send, sections, can you please comment more on that.

**Comment by kostat** [comment]
@rtandonmsft: POM - fixed version to 0.9.1, though the original was 0.9 and not 0.9.1. Regarding EventHubSEnder and sections: I want to allow sending any kind of section, not just Data. To be honest, I created a pull request just for getters and continued to made changes inside my branch. Due to an unclear reason GitHub actually took all my work and merged to the pull request, so it looks now a bit mess. It was not intentional.
More notes:
- How do you format your files? I'm using Eclipse on Windows with default Eclipse formatting + line = 120 chars. For some files the diff is correct, for others, like POM, it shows like the whole file is changed. My feeling is that EOL is not consistent, though not checked.
- I have few questions regarding ResilientEventHubReceiver:
  1. What is the issue you refer there "AMQP/EH bug of failing to receive messages"?
  1. It looks like an intended way to create a receiver is EventHubClient -> getConsumerGroup() -> createReceiver(). It creates a plain EventHubReceiver. Is this way supported?

**Comment by rtandonmsft** [comment]
@kostat I have merged your changes into master. I have some changes that I am doing to re-establish EventHubSender connection on failure, and wanted to handle the error for your new send method as well. Will test your changes with mine and then publish an update.

* Format EOL - We use this within our team: https://issues.apache.org/jira/browse/HBASE-3678
* ResilientEventHubReceiver:
  * There is problem in the AMQP/QPID protocol that we found during testing where the receiver gets stalled and does not receive any more messages. To avoid that issue, we added a detection strategy that checks if things have not moved and reset the connections. As per the EventHubs team, these are the limitations of AMQP/QPID and they plan to provide a Proton-J based client in future. For now, this work-around has been deployed successfully and addressed the issue at hand.
* Yes, it should work. One can choose to use ConsumerGroups with EH in this client or use the client directly without specifying any consumer groups.

**Comment by kostat** [comment]
@rtandonmsft: I'm really surprised how fast and simple you accept pull requests. This makes contributing a pleasure!
I'm a bit confused with your last answer: the flow I refer in (ii) does not create the ResilientEventHubReceiver. And therefore the issue is not addressed. Do I miss something?

**Comment by rtandonmsft** [comment]
@kostat 
- It's a budding community and lot of people want to use EventHubs. Having easier processes and faster code velocity allows people to iterate faster.
- My saving grace for now is AppVeyor integration that had already ran a build for your PR automatically and told me all tests passed. If anything goes bad, I would rather invest in enhancing the tests and addressing the issue.

I also get your point regarding the ConsumerGroup.CreateReceiver better now. You pointed out correctly it does not create the ResilientVersion, it needs to be updated, so one may indeed hit the issue of stalling. I haven't tested that if problem repros with ConsumerGroups, but we should address it nonetheless.

The more I think about the problem, we should have just patched the existing receiver and not provide two versions until a new library or protocol improved. I don't it fun when users find out later that they were using the wrong class.

I wish it was done better. For now, let's get this fixed as we test it. Hopefully with more contributions the library will be in better shape.

**Pull request merged**
